version: "3"

volumes:
  redis_data: {}
  postres_data: {}

services:
  redis:
    image: redis
    restart: "unless-stopped"
    ports:
      - 6379:6379
    volumes:
      - "redis_data:/data"

  dgraph:
    image: dgraph/standalone:v21.03.0
    restart: "unless-stopped"
    ports:
      - 8080:8080
      - 9080:9080

  postgres:
    image: postgres
    restart: "unless-stopped"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: titan
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "postres_data:/var/lib/postgresql/data"
      - "./postgres:/docker-entrypoint-initdb.d"
