apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: titan
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: titan
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
