name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker Image
        run: |
          export TAG=`expr substr $GITHUB_SHA 1 8`
          export DOCKER_HUB_IMAGE=oxisto/titan
          echo "{\"version\": \"${TAG}\"}" > frontend/src/assets/config.json
          docker build -t $DOCKER_HUB_IMAGE:$TAG .
      - name: Push Docker Image
        run: |
          export TAG=`expr substr $GITHUB_SHA 1 8`
          export DOCKER_HUB_IMAGE=oxisto/titan
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag $DOCKER_HUB_IMAGE:$TAG $DOCKER_HUB_IMAGE 
          docker push $DOCKER_HUB_IMAGE:$TAG
          docker push $DOCKER_HUB_IMAGE
        if: github.ref == 'refs/heads/master'
      - name: Deploy Kubernetes
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl
          mkdir -p ~/.kube && echo ${{ secrets.KUBECONFIG_BASE64 }} | base64 -d > ~/.kube/config
          export TAG=`expr substr $GITHUB_SHA 1 8`
          envsubst < kubernetes/postgres.yaml | kubectl apply -f -
          envsubst < kubernetes/redis.yaml | kubectl apply -f -
          envsubst < kubernetes/titan.yaml | kubectl apply -f -
        if: github.ref == 'refs/heads/master'
